### ISSUE TITLE
This product is completely unusable in its current state

### ISSUE THREAD

**Issue by blairg23** [github-tools/github-release-notes#228] opened 2019-12-06 18:09 UTC
This issue has not been addressed and causes the product to create an incorrect solution.

https://github.com/github-tools/github-release-notes/issues/219

Currently if I release a version at commit `abcd1234` that contains the following commits:

```
abcd1234 - tagged v2
efgh1234
ijkl1234
mnop1234
qrst1234 - tagged v1
```

The resulting "release notes" will contain `efgh1234` through `qrst1234`, but will be missing `abcd1234`. Similarly, v1 is missing `qrst1234`... This is an incorrect representation of what has been released, as I am also releasing `abcd1234` and I am NOT releasing `qrst1234` as it was released in v1!!

**Comment by alexcanessa** [comment] 2019-12-12 10:28
I'm doing some checks now to see if it's only the `dataSource=commits` that is broken or the whole thing and I'll reflect the status on the README file.

**Comment by alexcanessa** [comment] 2019-12-12 15:07
Commits should be now fixed. I'm releasing `0.17.1` and that should do.

Anyway, it's a duplicate of #229

**Closed by alexcanessa** 2019-12-12 15:07 UTC
Labels: duplicate
